import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const TOURNAMENT_ID = 't1';
const MODE: 'reset' | 'append' = (process.env.SEED_MODE as any) ?? 'append';

const groups: Array<{ id: string; name: string }> = [
  { id: 'A', name: 'Grupa A' },
  { id: 'B', name: 'Grupa B' },
  { id: 'C', name: 'Grupa C' },
  { id: 'D', name: 'Grupa D' },
];

const stages: Array<{
  id: string;
  name: string;
  kind: 'GROUP' | 'PLAYOFF';
  order: number;
}> = [
  { id: 'STAGE-GRP-1', name: 'Faza grupowa', kind: 'GROUP', order: 1 },
  { id: 'STAGE-PO-1', name: 'Play-off', kind: 'PLAYOFF', order: 2 },
];

const STAGE_GRP = 'STAGE-GRP-1';
const STAGE_PO = 'STAGE-PO-1';

type TeamSeed = {
  id: string;
  name: string;
  logo?: string;
  playerIds: string[];
  groupId: string;
};
const teams: TeamSeed[] = [
  {
    id: 'T1',
    name: 'Lech Poznań',
    logo: 'assets/LOGA/LECH-POZNAN-LOGO.jpg',
    playerIds: [
      'P1',
      'P2',
      'P3',
      'P4',
      'P5',
      'P6',
      'P7',
      'P8',
      'P9',
      'P10',
      'P11',
      'P12',
      'P13',
      'P14',
      'P15',
    ],
    groupId: 'A',
  },
  {
    id: 'T2',
    name: 'Motor Lublin',
    logo: 'assets/LOGA/MOTOR-LUBLIN-LOGO.jpg',
    playerIds: [
      'P16',
      'P17',
      'P18',
      'P19',
      'P20',
      'P21',
      'P22',
      'P23',
      'P24',
      'P25',
      'P26',
      'P27',
      'P28',
      'P29',
      'P30',
    ],
    groupId: 'A',
  },
  {
    id: 'T3',
    name: 'Arka Gdynia',
    logo: 'assets/LOGA/ARKA-GDYNIA-LOGO.jpg',
    playerIds: [
      'P31',
      'P32',
      'P33',
      'P34',
      'P35',
      'P36',
      'P37',
      'P38',
      'P39',
      'P40',
      'P41',
      'P42',
      'P43',
      'P44',
      'P45',
    ],
    groupId: 'A',
  },
  {
    id: 'T4',
    name: 'Widzew Łódź',
    logo: 'assets/LOGA/WIDZEW-LODZ-LOGO.jpg',
    playerIds: [
      'P46',
      'P47',
      'P48',
      'P49',
      'P50',
      'P51',
      'P52',
      'P53',
      'P54',
      'P55',
      'P56',
      'P57',
      'P58',
      'P59',
      'P60',
    ],
    groupId: 'A',
  },
  {
    id: 'T5',
    name: 'Pogoń Szczecin',
    logo: 'assets/LOGA/POGON-SZCZECIN-LOGO.jpg',
    playerIds: [
      'P61',
      'P62',
      'P63',
      'P64',
      'P65',
      'P66',
      'P67',
      'P68',
      'P69',
      'P70',
      'P71',
      'P72',
      'P73',
      'P74',
      'P75',
    ],
    groupId: 'B',
  },
  {
    id: 'T6',
    name: 'Wisła Płock',
    logo: 'assets/LOGA/WISLA-PLOCK-LOGO.png',
    playerIds: [
      'P76',
      'P77',
      'P78',
      'P79',
      'P80',
      'P81',
      'P82',
      'P83',
      'P84',
      'P85',
      'P86',
      'P87',
      'P88',
      'P89',
      'P90',
    ],
    groupId: 'B',
  },
  {
    id: 'T7',
    name: 'Jagiellonia Białystok',
    logo: 'assets/LOGA/JAGIELONIA-BIALYSTOK-LOGO.jpg',
    playerIds: [
      'P91',
      'P92',
      'P93',
      'P94',
      'P95',
      'P96',
      'P97',
      'P98',
      'P99',
      'P100',
      'P101',
      'P102',
      'P103',
      'P104',
      'P105',
    ],
    groupId: 'B',
  },
  {
    id: 'T8',
    name: 'Korona Kielce',
    logo: 'assets/LOGA/KORONA-KIELCE-LOGO.jpg',
    playerIds: [
      'P106',
      'P107',
      'P108',
      'P109',
      'P110',
      'P111',
      'P112',
      'P113',
      'P114',
      'P115',
      'P116',
      'P117',
      'P118',
      'P119',
      'P120',
    ],
    groupId: 'B',
  },
  {
    id: 'T9',
    name: 'Raków Częstochowa',
    logo: 'assets/LOGA/RAKOW-CZESTOCHOWA-LOGO.png',
    playerIds: [
      'P121',
      'P122',
      'P123',
      'P124',
      'P125',
      'P126',
      'P127',
      'P128',
      'P129',
      'P130',
      'P131',
      'P132',
      'P133',
      'P134',
      'P135',
    ],
    groupId: 'C',
  },
  {
    id: 'T10',
    name: 'Piast Gliwice',
    logo: 'assets/LOGA/PIAST-GLIWICE-LOGO.png',
    playerIds: [
      'P136',
      'P137',
      'P138',
      'P139',
      'P140',
      'P141',
      'P142',
      'P143',
      'P144',
      'P145',
      'P146',
      'P147',
      'P148',
      'P149',
      'P150',
    ],
    groupId: 'C',
  },
  {
    id: 'T11',
    name: 'Radomiak Radom',
    logo: 'assets/LOGA/RADOMIAK-RADOM-LOGO.jpg',
    playerIds: [
      'P151',
      'P152',
      'P153',
      'P154',
      'P155',
      'P156',
      'P157',
      'P158',
      'P159',
      'P160',
      'P161',
      'P162',
      'P163',
      'P164',
      'P165',
    ],
    groupId: 'C',
  },
  {
    id: 'T12',
    name: 'Cracovia',
    logo: 'assets/LOGA/CRACOVIA-LOGO.png',
    playerIds: [
      'P166',
      'P167',
      'P168',
      'P169',
      'P170',
      'P171',
      'P172',
      'P173',
      'P174',
      'P175',
      'P176',
      'P177',
      'P178',
      'P179',
      'P180',
    ],
    groupId: 'C',
  },
  {
    id: 'T13',
    name: 'GKS Katowice',
    logo: 'assets/LOGA/GKS-KATOWICE-LOGO.jpg',
    playerIds: [
      'P181',
      'P182',
      'P183',
      'P184',
      'P185',
      'P186',
      'P187',
      'P188',
      'P189',
      'P190',
      'P191',
      'P192',
      'P193',
      'P194',
      'P195',
    ],
    groupId: 'D',
  },
  {
    id: 'T14',
    name: 'KGHM Zagłębie Lubin',
    logo: 'assets/LOGA/ZAGLEBIE-LUBIN-LOGO.jpg',
    playerIds: [
      'P196',
      'P197',
      'P198',
      'P199',
      'P200',
      'P201',
      'P202',
      'P203',
      'P204',
      'P205',
      'P206',
      'P207',
      'P208',
      'P209',
      'P210',
    ],
    groupId: 'D',
  },
  {
    id: 'T15',
    name: 'Bruk-Bet Termalica Nieciecza',
    logo: 'assets/LOGA/TERMALICA-NIECIECZA-LOGO.png',
    playerIds: [
      'P211',
      'P212',
      'P213',
      'P214',
      'P215',
      'P216',
      'P217',
      'P218',
      'P219',
      'P220',
      'P221',
      'P222',
      'P223',
      'P224',
      'P225',
    ],
    groupId: 'D',
  },
  {
    id: 'T16',
    name: 'Górnik Zabrze',
    logo: 'assets/LOGA/GORNIK-ZABRZE-LOGO.jpg',
    playerIds: [
      'P226',
      'P227',
      'P228',
      'P229',
      'P230',
      'P231',
      'P232',
      'P233',
      'P234',
      'P235',
      'P236',
      'P237',
      'P238',
      'P239',
      'P240',
    ],
    groupId: 'D',
  },
];

// players: id, teamId, name, position, shirtNumber?, healthStatus
type PlayerSeed = {
  id: string;
  teamId: string;
  name: string;
  position: 'GK' | 'DEF' | 'MID' | 'FWD';
  shirtNumber?: number;
  healthStatus: 'HEALTHY' | 'INJURED';
};
const players: PlayerSeed[] = [
  // TODO: wklej całość (P1..P240)
  // { id: 'P1', teamId: 'T1', name: 'Kacper Kubiak', position: 'GK', shirtNumber: 1, healthStatus: 'HEALTHY' },
  {
    id: 'P1',
    teamId: 'T1',
    name: 'Kacper Kubiak',
    position: 'GK',
    shirtNumber: 1,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P2',
    teamId: 'T1',
    name: 'Michał Lis',
    position: 'GK',
    shirtNumber: 12,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P3',
    teamId: 'T1',
    name: 'Tomasz Wójcik',
    position: 'FWD',
    shirtNumber: 9,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P4',
    teamId: 'T1',
    name: 'Jakub Pawlak',
    position: 'FWD',
    shirtNumber: 11,
    healthStatus: 'INJURED',
  },
  {
    id: 'P5',
    teamId: 'T1',
    name: 'Patryk Majewski',
    position: 'FWD',
    shirtNumber: 7,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P6',
    teamId: 'T1',
    name: 'Mateusz Król',
    position: 'DEF',
    shirtNumber: 2,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P7',
    teamId: 'T1',
    name: 'Adrian Szymański',
    position: 'DEF',
    shirtNumber: 3,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P8',
    teamId: 'T1',
    name: 'Łukasz Kaczmarek',
    position: 'DEF',
    shirtNumber: 4,
    healthStatus: 'INJURED',
  },
  {
    id: 'P9',
    teamId: 'T1',
    name: 'Paweł Zawadzki',
    position: 'DEF',
    shirtNumber: 5,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P10',
    teamId: 'T1',
    name: 'Grzegorz Malinowski',
    position: 'DEF',
    shirtNumber: 6,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P11',
    teamId: 'T1',
    name: 'Rafał Kowalczyk',
    position: 'MID',
    shirtNumber: 8,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P12',
    teamId: 'T1',
    name: 'Damian Baran',
    position: 'MID',
    shirtNumber: 10,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P13',
    teamId: 'T1',
    name: 'Krzysztof Jasiński',
    position: 'MID',
    shirtNumber: 13,
    healthStatus: 'INJURED',
  },
  {
    id: 'P14',
    teamId: 'T1',
    name: 'Robert Górski',
    position: 'MID',
    shirtNumber: 14,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P15',
    teamId: 'T1',
    name: 'Sebastian Wilk',
    position: 'MID',
    shirtNumber: 15,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P16',
    teamId: 'T2',
    name: 'Zdzisław Stonoga',
    position: 'GK',
    shirtNumber: 1,
    healthStatus: 'INJURED',
  },
  {
    id: 'P17',
    teamId: 'T2',
    name: 'Marek Wróbel',
    position: 'GK',
    shirtNumber: 12,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P18',
    teamId: 'T2',
    name: 'Kamil Borowski',
    position: 'FWD',
    shirtNumber: 9,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P19',
    teamId: 'T2',
    name: 'Łukasz Pawlik',
    position: 'FWD',
    shirtNumber: 11,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P20',
    teamId: 'T2',
    name: 'Adrian Kamiński',
    position: 'FWD',
    shirtNumber: 7,
    healthStatus: 'INJURED',
  },
  {
    id: 'P21',
    teamId: 'T2',
    name: 'Dominik Bednarek',
    position: 'DEF',
    shirtNumber: 2,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P22',
    teamId: 'T2',
    name: 'Piotr Marciniak',
    position: 'DEF',
    shirtNumber: 3,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P23',
    teamId: 'T2',
    name: 'Radosław Urban',
    position: 'DEF',
    shirtNumber: 4,
    healthStatus: 'INJURED',
  },
  {
    id: 'P24',
    teamId: 'T2',
    name: 'Patryk Musiał',
    position: 'DEF',
    shirtNumber: 5,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P25',
    teamId: 'T2',
    name: 'Maciej Królak',
    position: 'DEF',
    shirtNumber: 6,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P26',
    teamId: 'T2',
    name: 'Jakub Nowicki',
    position: 'MID',
    shirtNumber: 8,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P27',
    teamId: 'T2',
    name: 'Tomasz Bartek',
    position: 'MID',
    shirtNumber: 10,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P28',
    teamId: 'T2',
    name: 'Mateusz Żuraw',
    position: 'MID',
    shirtNumber: 13,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P29',
    teamId: 'T2',
    name: 'Krzysztof Czarnecki',
    position: 'MID',
    shirtNumber: 14,
    healthStatus: 'INJURED',
  },
  {
    id: 'P30',
    teamId: 'T2',
    name: 'Damian Orłowski',
    position: 'MID',
    shirtNumber: 15,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P31',
    teamId: 'T3',
    name: 'Bartłomiej Chmielewski',
    position: 'GK',
    shirtNumber: 1,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P32',
    teamId: 'T3',
    name: 'Mariusz Olejniczak',
    position: 'GK',
    shirtNumber: 12,
    healthStatus: 'INJURED',
  },
  {
    id: 'P33',
    teamId: 'T3',
    name: 'Piotr Dąbrowski',
    position: 'FWD',
    shirtNumber: 9,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P34',
    teamId: 'T3',
    name: 'Karol Sienkiewicz',
    position: 'FWD',
    shirtNumber: 11,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P35',
    teamId: 'T3',
    name: 'Damian Rutkowski',
    position: 'FWD',
    shirtNumber: 7,
    healthStatus: 'INJURED',
  },
  {
    id: 'P36',
    teamId: 'T3',
    name: 'Marcin Krawczyk',
    position: 'DEF',
    shirtNumber: 2,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P37',
    teamId: 'T3',
    name: 'Adrian Walczak',
    position: 'DEF',
    shirtNumber: 3,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P38',
    teamId: 'T3',
    name: 'Patryk Gajewski',
    position: 'DEF',
    shirtNumber: 4,
    healthStatus: 'INJURED',
  },
  {
    id: 'P39',
    teamId: 'T3',
    name: 'Rafał Kozłowski',
    position: 'DEF',
    shirtNumber: 5,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P40',
    teamId: 'T3',
    name: 'Michał Stefański',
    position: 'DEF',
    shirtNumber: 6,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P41',
    teamId: 'T3',
    name: 'Tomasz Polak',
    position: 'MID',
    shirtNumber: 8,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P42',
    teamId: 'T3',
    name: 'Konrad Dudek',
    position: 'MID',
    shirtNumber: 10,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P43',
    teamId: 'T3',
    name: 'Łukasz Borkowski',
    position: 'MID',
    shirtNumber: 13,
    healthStatus: 'INJURED',
  },
  {
    id: 'P44',
    teamId: 'T3',
    name: 'Sebastian Ratajczak',
    position: 'MID',
    shirtNumber: 14,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P45',
    teamId: 'T3',
    name: 'Norbert Wieczorek',
    position: 'MID',
    shirtNumber: 15,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P46',
    teamId: 'T4',
    name: 'Mariusz Sobczak',
    position: 'GK',
    shirtNumber: 1,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P47',
    teamId: 'T4',
    name: 'Paweł Frąckowiak',
    position: 'GK',
    shirtNumber: 12,
    healthStatus: 'INJURED',
  },
  {
    id: 'P48',
    teamId: 'T4',
    name: 'Radosław Wojciechowski',
    position: 'FWD',
    shirtNumber: 9,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P49',
    teamId: 'T4',
    name: 'Łukasz Zięba',
    position: 'FWD',
    shirtNumber: 11,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P50',
    teamId: 'T4',
    name: 'Patryk Sadowski',
    position: 'FWD',
    shirtNumber: 7,
    healthStatus: 'INJURED',
  },
  {
    id: 'P51',
    teamId: 'T4',
    name: 'Tomasz Rybak',
    position: 'DEF',
    shirtNumber: 2,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P52',
    teamId: 'T4',
    name: 'Adrian Sobolewski',
    position: 'DEF',
    shirtNumber: 3,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P53',
    teamId: 'T4',
    name: 'Mateusz Wieczorek',
    position: 'DEF',
    shirtNumber: 4,
    healthStatus: 'INJURED',
  },
  {
    id: 'P54',
    teamId: 'T4',
    name: 'Michał Pawlicki',
    position: 'DEF',
    shirtNumber: 5,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P55',
    teamId: 'T4',
    name: 'Grzegorz Tomczak',
    position: 'DEF',
    shirtNumber: 6,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P56',
    teamId: 'T4',
    name: 'Damian Szulc',
    position: 'MID',
    shirtNumber: 8,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P57',
    teamId: 'T4',
    name: 'Krzysztof Błaszczyk',
    position: 'MID',
    shirtNumber: 10,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P58',
    teamId: 'T4',
    name: 'Sebastian Lisowski',
    position: 'MID',
    shirtNumber: 13,
    healthStatus: 'INJURED',
  },
  {
    id: 'P59',
    teamId: 'T4',
    name: 'Piotr Nowaczyk',
    position: 'MID',
    shirtNumber: 14,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P60',
    teamId: 'T4',
    name: 'Jakub Ostrowski',
    position: 'MID',
    shirtNumber: 15,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P61',
    teamId: 'T5',
    name: 'Kamil Rosiak',
    position: 'GK',
    shirtNumber: 1,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P62',
    teamId: 'T5',
    name: 'Paweł Konieczny',
    position: 'GK',
    shirtNumber: 12,
    healthStatus: 'INJURED',
  },
  {
    id: 'P63',
    teamId: 'T5',
    name: 'Michał Żebrowski',
    position: 'FWD',
    shirtNumber: 9,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P64',
    teamId: 'T5',
    name: 'Adrian Kowalewski',
    position: 'FWD',
    shirtNumber: 11,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P65',
    teamId: 'T5',
    name: 'Damian Łuczak',
    position: 'FWD',
    shirtNumber: 7,
    healthStatus: 'INJURED',
  },
  {
    id: 'P66',
    teamId: 'T5',
    name: 'Rafał Wilczyński',
    position: 'DEF',
    shirtNumber: 2,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P67',
    teamId: 'T5',
    name: 'Łukasz Kalinowski',
    position: 'DEF',
    shirtNumber: 3,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P68',
    teamId: 'T5',
    name: 'Patryk Domagała',
    position: 'DEF',
    shirtNumber: 4,
    healthStatus: 'INJURED',
  },
  {
    id: 'P69',
    teamId: 'T5',
    name: 'Grzegorz Wołosz',
    position: 'DEF',
    shirtNumber: 5,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P70',
    teamId: 'T5',
    name: 'Mateusz Dudek',
    position: 'DEF',
    shirtNumber: 6,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P71',
    teamId: 'T5',
    name: 'Karol Zając',
    position: 'MID',
    shirtNumber: 8,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P72',
    teamId: 'T5',
    name: 'Robert Małecki',
    position: 'MID',
    shirtNumber: 10,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P73',
    teamId: 'T5',
    name: 'Sebastian Banaś',
    position: 'MID',
    shirtNumber: 13,
    healthStatus: 'INJURED',
  },
  {
    id: 'P74',
    teamId: 'T5',
    name: 'Krzysztof Leśniak',
    position: 'MID',
    shirtNumber: 14,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P75',
    teamId: 'T5',
    name: 'Tomasz Olczak',
    position: 'MID',
    shirtNumber: 15,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P76',
    teamId: 'T6',
    name: 'Maciej Rutkowski',
    position: 'GK',
    shirtNumber: 1,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P77',
    teamId: 'T6',
    name: 'Tomasz Sikora',
    position: 'GK',
    shirtNumber: 12,
    healthStatus: 'INJURED',
  },
  {
    id: 'P78',
    teamId: 'T6',
    name: 'Krzysztof Bednarek',
    position: 'FWD',
    shirtNumber: 9,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P79',
    teamId: 'T6',
    name: 'Radosław Piątek',
    position: 'FWD',
    shirtNumber: 11,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P80',
    teamId: 'T6',
    name: 'Damian Frączak',
    position: 'FWD',
    shirtNumber: 7,
    healthStatus: 'INJURED',
  },
  {
    id: 'P81',
    teamId: 'T6',
    name: 'Łukasz Małek',
    position: 'DEF',
    shirtNumber: 2,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P82',
    teamId: 'T6',
    name: 'Patryk Rosiński',
    position: 'DEF',
    shirtNumber: 3,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P83',
    teamId: 'T6',
    name: 'Adrian Kołodziej',
    position: 'DEF',
    shirtNumber: 4,
    healthStatus: 'INJURED',
  },
  {
    id: 'P84',
    teamId: 'T6',
    name: 'Michał Raczkowski',
    position: 'DEF',
    shirtNumber: 5,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P85',
    teamId: 'T6',
    name: 'Piotr Janicki',
    position: 'DEF',
    shirtNumber: 6,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P86',
    teamId: 'T6',
    name: 'Grzegorz Sobieraj',
    position: 'MID',
    shirtNumber: 8,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P87',
    teamId: 'T6',
    name: 'Mateusz Kubicki',
    position: 'MID',
    shirtNumber: 10,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P88',
    teamId: 'T6',
    name: 'Sebastian Cieślak',
    position: 'MID',
    shirtNumber: 13,
    healthStatus: 'INJURED',
  },
  {
    id: 'P89',
    teamId: 'T6',
    name: 'Kamil Górniak',
    position: 'MID',
    shirtNumber: 14,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P90',
    teamId: 'T6',
    name: 'Norbert Michalak',
    position: 'MID',
    shirtNumber: 15,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P91',
    teamId: 'T7',
    name: 'Rafał Głowacki',
    position: 'GK',
    shirtNumber: 1,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P92',
    teamId: 'T7',
    name: 'Damian Stasiak',
    position: 'GK',
    shirtNumber: 12,
    healthStatus: 'INJURED',
  },
  {
    id: 'P93',
    teamId: 'T7',
    name: 'Michał Andrzejewski',
    position: 'FWD',
    shirtNumber: 9,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P94',
    teamId: 'T7',
    name: 'Patryk Chojnacki',
    position: 'FWD',
    shirtNumber: 11,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P95',
    teamId: 'T7',
    name: 'Krzysztof Wieczorek',
    position: 'FWD',
    shirtNumber: 7,
    healthStatus: 'INJURED',
  },
  {
    id: 'P96',
    teamId: 'T7',
    name: 'Mateusz Kozieł',
    position: 'DEF',
    shirtNumber: 2,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P97',
    teamId: 'T7',
    name: 'Piotr Orzechowski',
    position: 'DEF',
    shirtNumber: 3,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P98',
    teamId: 'T7',
    name: 'Łukasz Skrzypczak',
    position: 'DEF',
    shirtNumber: 4,
    healthStatus: 'INJURED',
  },
  {
    id: 'P99',
    teamId: 'T7',
    name: 'Tomasz Kurowski',
    position: 'DEF',
    shirtNumber: 5,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P100',
    teamId: 'T7',
    name: 'Adrian Sobieraj',
    position: 'DEF',
    shirtNumber: 6,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P101',
    teamId: 'T7',
    name: 'Maciej Matusiak',
    position: 'MID',
    shirtNumber: 8,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P102',
    teamId: 'T7',
    name: 'Kamil Szczepański',
    position: 'MID',
    shirtNumber: 10,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P103',
    teamId: 'T7',
    name: 'Sebastian Kaczor',
    position: 'MID',
    shirtNumber: 13,
    healthStatus: 'INJURED',
  },
  {
    id: 'P104',
    teamId: 'T7',
    name: 'Norbert Adamczyk',
    position: 'MID',
    shirtNumber: 14,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P105',
    teamId: 'T7',
    name: 'Grzegorz Kołodziej',
    position: 'MID',
    shirtNumber: 15,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P106',
    teamId: 'T8',
    name: 'Łukasz Wilczyński',
    position: 'GK',
    shirtNumber: 1,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P107',
    teamId: 'T8',
    name: 'Kamil Olejnik',
    position: 'GK',
    shirtNumber: 12,
    healthStatus: 'INJURED',
  },
  {
    id: 'P108',
    teamId: 'T8',
    name: 'Tomasz Jarosz',
    position: 'FWD',
    shirtNumber: 9,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P109',
    teamId: 'T8',
    name: 'Paweł Czajkowski',
    position: 'FWD',
    shirtNumber: 11,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P110',
    teamId: 'T8',
    name: 'Radosław Sowa',
    position: 'FWD',
    shirtNumber: 7,
    healthStatus: 'INJURED',
  },
  {
    id: 'P111',
    teamId: 'T8',
    name: 'Mateusz Krysiak',
    position: 'DEF',
    shirtNumber: 2,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P112',
    teamId: 'T8',
    name: 'Adrian Kubiak',
    position: 'DEF',
    shirtNumber: 3,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P113',
    teamId: 'T8',
    name: 'Michał Kaleta',
    position: 'DEF',
    shirtNumber: 4,
    healthStatus: 'INJURED',
  },
  {
    id: 'P114',
    teamId: 'T8',
    name: 'Krzysztof Rogalski',
    position: 'DEF',
    shirtNumber: 5,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P115',
    teamId: 'T8',
    name: 'Damian Żak',
    position: 'DEF',
    shirtNumber: 6,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P116',
    teamId: 'T8',
    name: 'Maciej Owczarek',
    position: 'MID',
    shirtNumber: 8,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P117',
    teamId: 'T8',
    name: 'Patryk Cichoń',
    position: 'MID',
    shirtNumber: 10,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P118',
    teamId: 'T8',
    name: 'Sebastian Nowiński',
    position: 'MID',
    shirtNumber: 13,
    healthStatus: 'INJURED',
  },
  {
    id: 'P119',
    teamId: 'T8',
    name: 'Norbert Duda',
    position: 'MID',
    shirtNumber: 14,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P120',
    teamId: 'T8',
    name: 'Grzegorz Ławniczak',
    position: 'MID',
    shirtNumber: 15,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P121',
    teamId: 'T9',
    name: 'Marek Bartoszewski',
    position: 'GK',
    shirtNumber: 1,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P122',
    teamId: 'T9',
    name: 'Paweł Szymczak',
    position: 'GK',
    shirtNumber: 12,
    healthStatus: 'INJURED',
  },
  {
    id: 'P123',
    teamId: 'T9',
    name: 'Radosław Kowalczyk',
    position: 'FWD',
    shirtNumber: 9,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P124',
    teamId: 'T9',
    name: 'Łukasz Wysocki',
    position: 'FWD',
    shirtNumber: 11,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P125',
    teamId: 'T9',
    name: 'Adrian Drzewiecki',
    position: 'FWD',
    shirtNumber: 7,
    healthStatus: 'INJURED',
  },
  {
    id: 'P126',
    teamId: 'T9',
    name: 'Mateusz Andrzejczak',
    position: 'DEF',
    shirtNumber: 2,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P127',
    teamId: 'T9',
    name: 'Kamil Kaczorowski',
    position: 'DEF',
    shirtNumber: 3,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P128',
    teamId: 'T9',
    name: 'Michał Stolarz',
    position: 'DEF',
    shirtNumber: 4,
    healthStatus: 'INJURED',
  },
  {
    id: 'P129',
    teamId: 'T9',
    name: 'Patryk Stępień',
    position: 'DEF',
    shirtNumber: 5,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P130',
    teamId: 'T9',
    name: 'Grzegorz Muszyński',
    position: 'DEF',
    shirtNumber: 6,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P131',
    teamId: 'T9',
    name: 'Damian Włodarczyk',
    position: 'MID',
    shirtNumber: 8,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P132',
    teamId: 'T9',
    name: 'Krzysztof Kozieł',
    position: 'MID',
    shirtNumber: 10,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P133',
    teamId: 'T9',
    name: 'Sebastian Żurawski',
    position: 'MID',
    shirtNumber: 13,
    healthStatus: 'INJURED',
  },
  {
    id: 'P134',
    teamId: 'T9',
    name: 'Norbert Oleksy',
    position: 'MID',
    shirtNumber: 14,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P135',
    teamId: 'T9',
    name: 'Piotr Bartnik',
    position: 'MID',
    shirtNumber: 15,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P136',
    teamId: 'T10',
    name: 'Tomasz Konopka',
    position: 'GK',
    shirtNumber: 1,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P137',
    teamId: 'T10',
    name: 'Michał Włodarczyk',
    position: 'GK',
    shirtNumber: 12,
    healthStatus: 'INJURED',
  },
  {
    id: 'P138',
    teamId: 'T10',
    name: 'Radosław Malec',
    position: 'FWD',
    shirtNumber: 9,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P139',
    teamId: 'T10',
    name: 'Patryk Górecki',
    position: 'FWD',
    shirtNumber: 11,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P140',
    teamId: 'T10',
    name: 'Krzysztof Bartosik',
    position: 'FWD',
    shirtNumber: 7,
    healthStatus: 'INJURED',
  },
  {
    id: 'P141',
    teamId: 'T10',
    name: 'Łukasz Czarnecki',
    position: 'DEF',
    shirtNumber: 2,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P142',
    teamId: 'T10',
    name: 'Grzegorz Piotrowski',
    position: 'DEF',
    shirtNumber: 3,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P143',
    teamId: 'T10',
    name: 'Mateusz Krzyżanowski',
    position: 'DEF',
    shirtNumber: 4,
    healthStatus: 'INJURED',
  },
  {
    id: 'P144',
    teamId: 'T10',
    name: 'Adrian Bielecki',
    position: 'DEF',
    shirtNumber: 5,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P145',
    teamId: 'T10',
    name: 'Damian Wrona',
    position: 'DEF',
    shirtNumber: 6,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P146',
    teamId: 'T10',
    name: 'Maciej Kopeć',
    position: 'MID',
    shirtNumber: 8,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P147',
    teamId: 'T10',
    name: 'Piotr Rosiński',
    position: 'MID',
    shirtNumber: 10,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P148',
    teamId: 'T10',
    name: 'Sebastian Filipiak',
    position: 'MID',
    shirtNumber: 13,
    healthStatus: 'INJURED',
  },
  {
    id: 'P149',
    teamId: 'T10',
    name: 'Norbert Dąbek',
    position: 'MID',
    shirtNumber: 14,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P150',
    teamId: 'T10',
    name: 'Rafał Ciechanowski',
    position: 'MID',
    shirtNumber: 15,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P151',
    teamId: 'T11',
    name: 'Marek Gawroński',
    position: 'GK',
    shirtNumber: 1,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P152',
    teamId: 'T11',
    name: 'Kamil Lis',
    position: 'GK',
    shirtNumber: 12,
    healthStatus: 'INJURED',
  },
  {
    id: 'P153',
    teamId: 'T11',
    name: 'Damian Czajka',
    position: 'FWD',
    shirtNumber: 9,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P154',
    teamId: 'T11',
    name: 'Patryk Adamczak',
    position: 'FWD',
    shirtNumber: 11,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P155',
    teamId: 'T11',
    name: 'Radosław Grzelak',
    position: 'FWD',
    shirtNumber: 7,
    healthStatus: 'INJURED',
  },
  {
    id: 'P156',
    teamId: 'T11',
    name: 'Adrian Rogowski',
    position: 'DEF',
    shirtNumber: 2,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P157',
    teamId: 'T11',
    name: 'Łukasz Wieczorek',
    position: 'DEF',
    shirtNumber: 3,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P158',
    teamId: 'T11',
    name: 'Grzegorz Kania',
    position: 'DEF',
    shirtNumber: 4,
    healthStatus: 'INJURED',
  },
  {
    id: 'P159',
    teamId: 'T11',
    name: 'Mateusz Sobol',
    position: 'DEF',
    shirtNumber: 5,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P160',
    teamId: 'T11',
    name: 'Norbert Michalski',
    position: 'DEF',
    shirtNumber: 6,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P161',
    teamId: 'T11',
    name: 'Piotr Krzyżak',
    position: 'MID',
    shirtNumber: 8,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P162',
    teamId: 'T11',
    name: 'Sebastian Kurek',
    position: 'MID',
    shirtNumber: 10,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P163',
    teamId: 'T11',
    name: 'Krzysztof Zawada',
    position: 'MID',
    shirtNumber: 13,
    healthStatus: 'INJURED',
  },
  {
    id: 'P164',
    teamId: 'T11',
    name: 'Maciej Gruszka',
    position: 'MID',
    shirtNumber: 14,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P165',
    teamId: 'T11',
    name: 'Damian Chrzanowski',
    position: 'MID',
    shirtNumber: 15,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P166',
    teamId: 'T12',
    name: 'Tomasz Bartosik',
    position: 'GK',
    shirtNumber: 1,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P167',
    teamId: 'T12',
    name: 'Michał Urban',
    position: 'GK',
    shirtNumber: 12,
    healthStatus: 'INJURED',
  },
  {
    id: 'P168',
    teamId: 'T12',
    name: 'Radosław Karpiński',
    position: 'FWD',
    shirtNumber: 9,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P169',
    teamId: 'T12',
    name: 'Damian Piątek',
    position: 'FWD',
    shirtNumber: 11,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P170',
    teamId: 'T12',
    name: 'Patryk Lech',
    position: 'FWD',
    shirtNumber: 7,
    healthStatus: 'INJURED',
  },
  {
    id: 'P171',
    teamId: 'T12',
    name: 'Łukasz Romanowski',
    position: 'DEF',
    shirtNumber: 2,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P172',
    teamId: 'T12',
    name: 'Mateusz Wójcik',
    position: 'DEF',
    shirtNumber: 3,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P173',
    teamId: 'T12',
    name: 'Adrian Pawlak',
    position: 'DEF',
    shirtNumber: 4,
    healthStatus: 'INJURED',
  },
  {
    id: 'P174',
    teamId: 'T12',
    name: 'Kamil Kozioł',
    position: 'DEF',
    shirtNumber: 5,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P175',
    teamId: 'T12',
    name: 'Grzegorz Nowicki',
    position: 'DEF',
    shirtNumber: 6,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P176',
    teamId: 'T12',
    name: 'Sebastian Wojda',
    position: 'MID',
    shirtNumber: 8,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P177',
    teamId: 'T12',
    name: 'Maciej Frączak',
    position: 'MID',
    shirtNumber: 10,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P178',
    teamId: 'T12',
    name: 'Norbert Zięba',
    position: 'MID',
    shirtNumber: 13,
    healthStatus: 'INJURED',
  },
  {
    id: 'P179',
    teamId: 'T12',
    name: 'Paweł Król',
    position: 'MID',
    shirtNumber: 14,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P180',
    teamId: 'T12',
    name: 'Damian Tomala',
    position: 'MID',
    shirtNumber: 15,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P181',
    teamId: 'T13',
    name: 'Marek Czarnecki',
    position: 'GK',
    shirtNumber: 1,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P182',
    teamId: 'T13',
    name: 'Kamil Kurek',
    position: 'GK',
    shirtNumber: 12,
    healthStatus: 'INJURED',
  },
  {
    id: 'P183',
    teamId: 'T13',
    name: 'Patryk Baran',
    position: 'FWD',
    shirtNumber: 9,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P184',
    teamId: 'T13',
    name: 'Damian Wojtas',
    position: 'FWD',
    shirtNumber: 11,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P185',
    teamId: 'T13',
    name: 'Łukasz Cieplak',
    position: 'FWD',
    shirtNumber: 7,
    healthStatus: 'INJURED',
  },
  {
    id: 'P186',
    teamId: 'T13',
    name: 'Radosław Misztal',
    position: 'DEF',
    shirtNumber: 2,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P187',
    teamId: 'T13',
    name: 'Mateusz Jurek',
    position: 'DEF',
    shirtNumber: 3,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P188',
    teamId: 'T13',
    name: 'Tomasz Oleksiak',
    position: 'DEF',
    shirtNumber: 4,
    healthStatus: 'INJURED',
  },
  {
    id: 'P189',
    teamId: 'T13',
    name: 'Grzegorz Chmiel',
    position: 'DEF',
    shirtNumber: 5,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P190',
    teamId: 'T13',
    name: 'Paweł Wrona',
    position: 'DEF',
    shirtNumber: 6,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P191',
    teamId: 'T13',
    name: 'Krzysztof Matys',
    position: 'MID',
    shirtNumber: 8,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P192',
    teamId: 'T13',
    name: 'Sebastian Wojtasik',
    position: 'MID',
    shirtNumber: 10,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P193',
    teamId: 'T13',
    name: 'Norbert Banach',
    position: 'MID',
    shirtNumber: 13,
    healthStatus: 'INJURED',
  },
  {
    id: 'P194',
    teamId: 'T13',
    name: 'Piotr Knap',
    position: 'MID',
    shirtNumber: 14,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P195',
    teamId: 'T13',
    name: 'Adrian Tokarski',
    position: 'MID',
    shirtNumber: 15,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P196',
    teamId: 'T14',
    name: 'Tomasz Kalinowski',
    position: 'GK',
    shirtNumber: 1,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P197',
    teamId: 'T14',
    name: 'Michał Wilk',
    position: 'GK',
    shirtNumber: 12,
    healthStatus: 'INJURED',
  },
  {
    id: 'P198',
    teamId: 'T14',
    name: 'Damian Szulc',
    position: 'FWD',
    shirtNumber: 9,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P199',
    teamId: 'T14',
    name: 'Paweł Kasprzak',
    position: 'FWD',
    shirtNumber: 11,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P200',
    teamId: 'T14',
    name: 'Radosław Chrzan',
    position: 'FWD',
    shirtNumber: 7,
    healthStatus: 'INJURED',
  },
  {
    id: 'P201',
    teamId: 'T14',
    name: 'Adrian Pawlicki',
    position: 'DEF',
    shirtNumber: 2,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P202',
    teamId: 'T14',
    name: 'Krzysztof Dudek',
    position: 'DEF',
    shirtNumber: 3,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P203',
    teamId: 'T14',
    name: 'Mateusz Błaszczyk',
    position: 'DEF',
    shirtNumber: 4,
    healthStatus: 'INJURED',
  },
  {
    id: 'P204',
    teamId: 'T14',
    name: 'Łukasz Sienkiewicz',
    position: 'DEF',
    shirtNumber: 5,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P205',
    teamId: 'T14',
    name: 'Patryk Nowiński',
    position: 'DEF',
    shirtNumber: 6,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P206',
    teamId: 'T14',
    name: 'Grzegorz Bartnik',
    position: 'MID',
    shirtNumber: 8,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P207',
    teamId: 'T14',
    name: 'Sebastian Olejniczak',
    position: 'MID',
    shirtNumber: 10,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P208',
    teamId: 'T14',
    name: 'Norbert Borowiec',
    position: 'MID',
    shirtNumber: 13,
    healthStatus: 'INJURED',
  },
  {
    id: 'P209',
    teamId: 'T14',
    name: 'Maciej Zakrzewski',
    position: 'MID',
    shirtNumber: 14,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P210',
    teamId: 'T14',
    name: 'Piotr Graczyk',
    position: 'MID',
    shirtNumber: 15,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P211',
    teamId: 'T15',
    name: 'Radosław Pawłowski',
    position: 'GK',
    shirtNumber: 1,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P212',
    teamId: 'T15',
    name: 'Kamil Wójcik',
    position: 'GK',
    shirtNumber: 12,
    healthStatus: 'INJURED',
  },
  {
    id: 'P213',
    teamId: 'T15',
    name: 'Damian Zielonka',
    position: 'FWD',
    shirtNumber: 9,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P214',
    teamId: 'T15',
    name: 'Patryk Grzelak',
    position: 'FWD',
    shirtNumber: 11,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P215',
    teamId: 'T15',
    name: 'Łukasz Tomczak',
    position: 'FWD',
    shirtNumber: 7,
    healthStatus: 'INJURED',
  },
  {
    id: 'P216',
    teamId: 'T15',
    name: 'Mateusz Dudkowski',
    position: 'DEF',
    shirtNumber: 2,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P217',
    teamId: 'T15',
    name: 'Piotr Łuczak',
    position: 'DEF',
    shirtNumber: 3,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P218',
    teamId: 'T15',
    name: 'Michał Pawlak',
    position: 'DEF',
    shirtNumber: 4,
    healthStatus: 'INJURED',
  },
  {
    id: 'P219',
    teamId: 'T15',
    name: 'Grzegorz Czajkowski',
    position: 'DEF',
    shirtNumber: 5,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P220',
    teamId: 'T15',
    name: 'Adrian Ratajczak',
    position: 'DEF',
    shirtNumber: 6,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P221',
    teamId: 'T15',
    name: 'Norbert Sadowski',
    position: 'MID',
    shirtNumber: 8,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P222',
    teamId: 'T15',
    name: 'Sebastian Marciniak',
    position: 'MID',
    shirtNumber: 10,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P223',
    teamId: 'T15',
    name: 'Maciej Czerniak',
    position: 'MID',
    shirtNumber: 13,
    healthStatus: 'INJURED',
  },
  {
    id: 'P224',
    teamId: 'T15',
    name: 'Krzysztof Radomski',
    position: 'MID',
    shirtNumber: 14,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P225',
    teamId: 'T15',
    name: 'Paweł Olejniczak',
    position: 'MID',
    shirtNumber: 15,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P226',
    teamId: 'T16',
    name: 'Michał Domański',
    position: 'GK',
    shirtNumber: 1,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P227',
    teamId: 'T16',
    name: 'Kamil Kaszuba',
    position: 'GK',
    shirtNumber: 12,
    healthStatus: 'INJURED',
  },
  {
    id: 'P228',
    teamId: 'T16',
    name: 'Damian Wójcik',
    position: 'FWD',
    shirtNumber: 9,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P229',
    teamId: 'T16',
    name: 'Patryk Brzeziński',
    position: 'FWD',
    shirtNumber: 11,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P230',
    teamId: 'T16',
    name: 'Łukasz Rosiak',
    position: 'FWD',
    shirtNumber: 7,
    healthStatus: 'INJURED',
  },
  {
    id: 'P231',
    teamId: 'T16',
    name: 'Mateusz Wojtaszek',
    position: 'DEF',
    shirtNumber: 2,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P232',
    teamId: 'T16',
    name: 'Grzegorz Sobczak',
    position: 'DEF',
    shirtNumber: 3,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P233',
    teamId: 'T16',
    name: 'Piotr Bartosik',
    position: 'DEF',
    shirtNumber: 4,
    healthStatus: 'INJURED',
  },
  {
    id: 'P234',
    teamId: 'T16',
    name: 'Adrian Błaszczyk',
    position: 'DEF',
    shirtNumber: 5,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P235',
    teamId: 'T16',
    name: 'Norbert Milewski',
    position: 'DEF',
    shirtNumber: 6,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P236',
    teamId: 'T16',
    name: 'Sebastian Domagała',
    position: 'MID',
    shirtNumber: 8,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P237',
    teamId: 'T16',
    name: 'Maciej Król',
    position: 'MID',
    shirtNumber: 10,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P238',
    teamId: 'T16',
    name: 'Radosław Leśniak',
    position: 'MID',
    shirtNumber: 13,
    healthStatus: 'INJURED',
  },
  {
    id: 'P239',
    teamId: 'T16',
    name: 'Krzysztof Janus',
    position: 'MID',
    shirtNumber: 14,
    healthStatus: 'HEALTHY',
  },
  {
    id: 'P240',
    teamId: 'T16',
    name: 'Damian Tokarski',
    position: 'MID',
    shirtNumber: 15,
    healthStatus: 'HEALTHY',
  },
];

type SeedMatch = {
  id: string;
  stageId: string;
  groupId?: string;
  round?: number;
  date: string;
  status: 'SCHEDULED' | 'LIVE' | 'FINISHED';
  homeTeamId: string;
  awayTeamId: string;
  score?: { home: number; away: number };
  events?: Array<{
    minute: number;
    type: 'GOAL' | 'ASSIST' | 'OWN_GOAL' | 'CARD';
    playerId: string;
    teamId: string;
    card?: 'YELLOW' | 'RED' | 'SECOND_YELLOW';
  }>;
  lineups?: {
    homeGKIds?: string[];
    awayGKIds?: string[];
  };
};

const matches: SeedMatch[] = [
  {
    id: 'M1',
    stageId: 'STAGE-GRP-1',
    groupId: 'A',
    round: 1,
    date: '2025-08-17T12:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T1',
    awayTeamId: 'T2',
    score: { home: 2, away: 1 },
    events: [
      { minute: 14, type: 'GOAL', playerId: 'P3', teamId: 'T1' },
      { minute: 14, type: 'ASSIST', playerId: 'P2', teamId: 'T1' },
      { minute: 39, type: 'OWN_GOAL', playerId: 'P3', teamId: 'T1' },
      { minute: 39, type: 'ASSIST', playerId: 'P19', teamId: 'T2' },
      { minute: 68, type: 'GOAL', playerId: 'P5', teamId: 'T1' },
      { minute: 68, type: 'ASSIST', playerId: 'P7', teamId: 'T1' },
      {
        minute: 77,
        type: 'CARD',
        playerId: 'P20',
        teamId: 'T2',
        card: 'RED',
      },
    ],
    lineups: {
      homeGKIds: ['P1'],
      awayGKIds: ['P16'],
    },
  },
  {
    id: 'M2',
    stageId: 'STAGE-GRP-1',
    groupId: 'A',
    round: 1,
    date: '2025-08-17T13:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T3',
    awayTeamId: 'T4',
    score: { home: 1, away: 1 },
    events: [
      { minute: 22, type: 'GOAL', playerId: 'P33', teamId: 'T3' },
      { minute: 22, type: 'ASSIST', playerId: 'P34', teamId: 'T3' },
      { minute: 61, type: 'GOAL', playerId: 'P52', teamId: 'T4' },
      { minute: 61, type: 'ASSIST', playerId: 'P48', teamId: 'T4' },
      {
        minute: 74,
        type: 'CARD',
        playerId: 'P38',
        teamId: 'T3',
        card: 'YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P31'],
      awayGKIds: ['P46'],
    },
  },
  {
    id: 'M3',
    stageId: 'STAGE-GRP-1',
    groupId: 'B',
    round: 1,
    date: '2025-08-17T14:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T5',
    awayTeamId: 'T6',
    score: { home: 0, away: 2 },
    events: [
      { minute: 36, type: 'GOAL', playerId: 'P79', teamId: 'T6' },
      { minute: 36, type: 'ASSIST', playerId: 'P81', teamId: 'T6' },
      { minute: 72, type: 'GOAL', playerId: 'P82', teamId: 'T6' },
      { minute: 72, type: 'ASSIST', playerId: 'P83', teamId: 'T6' },
      {
        minute: 64,
        type: 'CARD',
        playerId: 'P64',
        teamId: 'T5',
        card: 'YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P61'],
      awayGKIds: ['P76'],
    },
  },
  {
    id: 'M4',
    stageId: 'STAGE-GRP-1',
    groupId: 'B',
    round: 1,
    date: '2025-08-17T15:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T7',
    awayTeamId: 'T8',
    score: { home: 2, away: 2 },
    events: [
      { minute: 10, type: 'GOAL', playerId: 'P93', teamId: 'T7' },
      { minute: 10, type: 'ASSIST', playerId: 'P95', teamId: 'T7' },
      { minute: 27, type: 'GOAL', playerId: 'P108', teamId: 'T8' },
      { minute: 27, type: 'ASSIST', playerId: 'P111', teamId: 'T8' },
      { minute: 54, type: 'GOAL', playerId: 'P97', teamId: 'T7' },
      { minute: 54, type: 'ASSIST', playerId: 'P91', teamId: 'T7' },
      { minute: 81, type: 'GOAL', playerId: 'P112', teamId: 'T8' },
      { minute: 81, type: 'ASSIST', playerId: 'P109', teamId: 'T8' },
      {
        minute: 73,
        type: 'CARD',
        playerId: 'P99',
        teamId: 'T7',
        card: 'YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P91'],
      awayGKIds: ['P106'],
    },
  },
  {
    id: 'M5',
    stageId: 'STAGE-GRP-1',
    groupId: 'C',
    round: 1,
    date: '2025-08-17T16:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T9',
    awayTeamId: 'T10',
    score: { home: 1, away: 0 },
    events: [
      { minute: 66, type: 'GOAL', playerId: 'P124', teamId: 'T9' },
      { minute: 66, type: 'ASSIST', playerId: 'P123', teamId: 'T9' },
      {
        minute: 72,
        type: 'CARD',
        playerId: 'P139',
        teamId: 'T10',
        card: 'YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P121'],
      awayGKIds: ['P136'],
    },
  },
  {
    id: 'M6',
    stageId: 'STAGE-GRP-1',
    groupId: 'C',
    round: 1,
    date: '2025-08-17T17:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T11',
    awayTeamId: 'T12',
    score: { home: 2, away: 2 },
    events: [
      { minute: 8, type: 'GOAL', playerId: 'P152', teamId: 'T11' },
      { minute: 8, type: 'ASSIST', playerId: 'P154', teamId: 'T11' },
      { minute: 33, type: 'GOAL', playerId: 'P171', teamId: 'T12' },
      { minute: 33, type: 'ASSIST', playerId: 'P169', teamId: 'T12' },
      { minute: 59, type: 'GOAL', playerId: 'P156', teamId: 'T11' },
      { minute: 59, type: 'ASSIST', playerId: 'P158', teamId: 'T11' },
      { minute: 78, type: 'GOAL', playerId: 'P174', teamId: 'T12' },
      { minute: 78, type: 'ASSIST', playerId: 'P176', teamId: 'T12' },
      {
        minute: 82,
        type: 'CARD',
        playerId: 'P153',
        teamId: 'T11',
        card: 'YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P151'],
      awayGKIds: ['P166'],
    },
  },
  {
    id: 'M7',
    stageId: 'STAGE-GRP-1',
    groupId: 'D',
    round: 1,
    date: '2025-08-17T18:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T13',
    awayTeamId: 'T14',
    score: { home: 1, away: 3 },
    events: [
      { minute: 12, type: 'GOAL', playerId: 'P183', teamId: 'T13' },
      { minute: 12, type: 'ASSIST', playerId: 'P185', teamId: 'T13' },
      { minute: 27, type: 'GOAL', playerId: 'P197', teamId: 'T14' },
      { minute: 27, type: 'ASSIST', playerId: 'P199', teamId: 'T14' },
      { minute: 54, type: 'GOAL', playerId: 'P201', teamId: 'T14' },
      { minute: 54, type: 'ASSIST', playerId: 'P203', teamId: 'T14' },
      { minute: 81, type: 'GOAL', playerId: 'P200', teamId: 'T14' },
      { minute: 81, type: 'ASSIST', playerId: 'P202', teamId: 'T14' },
      {
        minute: 64,
        type: 'CARD',
        playerId: 'P193',
        teamId: 'T13',
        card: 'YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P181'],
      awayGKIds: ['P196'],
    },
  },
  {
    id: 'M8',
    stageId: 'STAGE-GRP-1',
    groupId: 'D',
    round: 1,
    date: '2025-08-17T19:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T15',
    awayTeamId: 'T16',
    score: { home: 2, away: 2 },
    events: [
      { minute: 18, type: 'GOAL', playerId: 'P213', teamId: 'T15' },
      { minute: 18, type: 'ASSIST', playerId: 'P214', teamId: 'T15' },
      { minute: 41, type: 'GOAL', playerId: 'P229', teamId: 'T16' },
      { minute: 41, type: 'ASSIST', playerId: 'P232', teamId: 'T16' },
      { minute: 55, type: 'GOAL', playerId: 'P219', teamId: 'T15' },
      { minute: 55, type: 'ASSIST', playerId: 'P222', teamId: 'T15' },
      { minute: 79, type: 'GOAL', playerId: 'P237', teamId: 'T16' },
      { minute: 79, type: 'ASSIST', playerId: 'P235', teamId: 'T16' },
      {
        minute: 66,
        type: 'CARD',
        playerId: 'P225',
        teamId: 'T15',
        card: 'YELLOW',
      },
      {
        minute: 74,
        type: 'CARD',
        playerId: 'P225',
        teamId: 'T15',
        card: 'SECOND_YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P211'],
      awayGKIds: ['P226'],
    },
  },
  {
    id: 'M9',
    stageId: 'STAGE-GRP-1',
    groupId: 'A',
    round: 2,
    date: '2025-08-24T12:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T1',
    awayTeamId: 'T3',
    score: { home: 1, away: 1 },
    events: [
      { minute: 24, type: 'GOAL', playerId: 'P7', teamId: 'T1' },
      { minute: 24, type: 'ASSIST', playerId: 'P2', teamId: 'T1' },
      { minute: 68, type: 'GOAL', playerId: 'P32', teamId: 'T3' },
      { minute: 68, type: 'ASSIST', playerId: 'P34', teamId: 'T3' },
      {
        minute: 77,
        type: 'CARD',
        playerId: 'P8',
        teamId: 'T1',
        card: 'YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P1'],
      awayGKIds: ['P31'],
    },
  },
  {
    id: 'M10',
    stageId: 'STAGE-GRP-1',
    groupId: 'A',
    round: 2,
    date: '2025-08-24T13:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T2',
    awayTeamId: 'T4',
    score: { home: 2, away: 0 },
    events: [
      { minute: 12, type: 'GOAL', playerId: 'P19', teamId: 'T2' },
      { minute: 12, type: 'ASSIST', playerId: 'P18', teamId: 'T2' },
      { minute: 54, type: 'GOAL', playerId: 'P22', teamId: 'T2' },
      { minute: 54, type: 'ASSIST', playerId: 'P20', teamId: 'T2' },
      {
        minute: 64,
        type: 'CARD',
        playerId: 'P51',
        teamId: 'T4',
        card: 'YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P16'],
      awayGKIds: ['P46'],
    },
  },
  {
    id: 'M11',
    stageId: 'STAGE-GRP-1',
    groupId: 'B',
    round: 2,
    date: '2025-08-24T14:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T5',
    awayTeamId: 'T7',
    score: { home: 1, away: 2 },
    events: [
      { minute: 21, type: 'GOAL', playerId: 'P33', teamId: 'T5' },
      { minute: 21, type: 'ASSIST', playerId: 'P37', teamId: 'T5' },
      { minute: 39, type: 'GOAL', playerId: 'P93', teamId: 'T7' },
      { minute: 39, type: 'ASSIST', playerId: 'P91', teamId: 'T7' },
      { minute: 71, type: 'GOAL', playerId: 'P97', teamId: 'T7' },
      { minute: 71, type: 'ASSIST', playerId: 'P95', teamId: 'T7' },
      {
        minute: 77,
        type: 'CARD',
        playerId: 'P63',
        teamId: 'T7',
        card: 'YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P61'],
      awayGKIds: ['P91'],
    },
  },
  {
    id: 'M12',
    stageId: 'STAGE-GRP-1',
    groupId: 'B',
    round: 2,
    date: '2025-08-24T15:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T6',
    awayTeamId: 'T8',
    score: { home: 2, away: 2 },
    events: [
      { minute: 19, type: 'GOAL', playerId: 'P79', teamId: 'T6' },
      { minute: 19, type: 'ASSIST', playerId: 'P81', teamId: 'T6' },
      { minute: 37, type: 'GOAL', playerId: 'P108', teamId: 'T8' },
      { minute: 37, type: 'ASSIST', playerId: 'P109', teamId: 'T8' },
      { minute: 62, type: 'GOAL', playerId: 'P82', teamId: 'T6' },
      { minute: 62, type: 'ASSIST', playerId: 'P83', teamId: 'T6' },
      { minute: 77, type: 'GOAL', playerId: 'P111', teamId: 'T8' },
      { minute: 77, type: 'ASSIST', playerId: 'P112', teamId: 'T8' },
      {
        minute: 85,
        type: 'CARD',
        playerId: 'P76',
        teamId: 'T6',
        card: 'YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P76'],
      awayGKIds: ['P106'],
    },
  },
  {
    id: 'M13',
    stageId: 'STAGE-GRP-1',
    groupId: 'C',
    round: 2,
    date: '2025-08-24T16:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T9',
    awayTeamId: 'T11',
    score: { home: 2, away: 1 },
    events: [
      { minute: 11, type: 'GOAL', playerId: 'P124', teamId: 'T9' },
      { minute: 11, type: 'ASSIST', playerId: 'P123', teamId: 'T9' },
      { minute: 44, type: 'GOAL', playerId: 'P152', teamId: 'T11' },
      { minute: 44, type: 'ASSIST', playerId: 'P154', teamId: 'T11' },
      { minute: 71, type: 'GOAL', playerId: 'P125', teamId: 'T9' },
      { minute: 71, type: 'ASSIST', playerId: 'P126', teamId: 'T9' },
      {
        minute: 74,
        type: 'CARD',
        playerId: 'P156',
        teamId: 'T11',
        card: 'YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P121'],
      awayGKIds: ['P151'],
    },
  },
  {
    id: 'M14',
    stageId: 'STAGE-GRP-1',
    groupId: 'C',
    round: 2,
    date: '2025-08-24T17:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T10',
    awayTeamId: 'T12',
    score: { home: 1, away: 1 },
    events: [
      { minute: 32, type: 'GOAL', playerId: 'P139', teamId: 'T10' },
      { minute: 32, type: 'ASSIST', playerId: 'P138', teamId: 'T10' },
      { minute: 59, type: 'GOAL', playerId: 'P171', teamId: 'T12' },
      { minute: 59, type: 'ASSIST', playerId: 'P176', teamId: 'T12' },
      {
        minute: 68,
        type: 'CARD',
        playerId: 'P147',
        teamId: 'T10',
        card: 'YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P136'],
      awayGKIds: ['P166'],
    },
  },
  {
    id: 'M15',
    stageId: 'STAGE-GRP-1',
    groupId: 'D',
    round: 2,
    date: '2025-08-24T18:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T13',
    awayTeamId: 'T15',
    score: { home: 3, away: 2 },
    events: [
      { minute: 10, type: 'GOAL', playerId: 'P183', teamId: 'T13' },
      { minute: 10, type: 'ASSIST', playerId: 'P184', teamId: 'T13' },
      { minute: 28, type: 'GOAL', playerId: 'P213', teamId: 'T15' },
      { minute: 28, type: 'ASSIST', playerId: 'P214', teamId: 'T15' },
      { minute: 46, type: 'GOAL', playerId: 'P185', teamId: 'T13' },
      { minute: 46, type: 'ASSIST', playerId: 'P188', teamId: 'T13' },
      { minute: 61, type: 'GOAL', playerId: 'P219', teamId: 'T15' },
      { minute: 61, type: 'ASSIST', playerId: 'P222', teamId: 'T15' },
      { minute: 74, type: 'GOAL', playerId: 'P189', teamId: 'T13' },
      { minute: 74, type: 'ASSIST', playerId: 'P190', teamId: 'T13' },
      {
        minute: 79,
        type: 'CARD',
        playerId: 'P225',
        teamId: 'T15',
        card: 'YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P181'],
      awayGKIds: ['P211'],
    },
  },
  {
    id: 'M16',
    stageId: 'STAGE-GRP-1',
    groupId: 'D',
    round: 2,
    date: '2025-08-24T19:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T14',
    awayTeamId: 'T16',
    score: { home: 0, away: 1 },
    events: [
      { minute: 53, type: 'GOAL', playerId: 'P229', teamId: 'T16' },
      { minute: 53, type: 'ASSIST', playerId: 'P234', teamId: 'T16' },
      {
        minute: 77,
        type: 'CARD',
        playerId: 'P197',
        teamId: 'T14',
        card: 'YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P196'],
      awayGKIds: ['P226'],
    },
  },
  {
    id: 'M17',
    stageId: 'STAGE-GRP-1',
    groupId: 'A',
    round: 3,
    date: '2025-08-29T12:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T1',
    awayTeamId: 'T4',
    score: { home: 1, away: 2 },
    events: [
      { minute: 15, type: 'GOAL', playerId: 'P5', teamId: 'T1' },
      { minute: 15, type: 'ASSIST', playerId: 'P7', teamId: 'T1' },
      { minute: 42, type: 'GOAL', playerId: 'P50', teamId: 'T4' },
      { minute: 42, type: 'ASSIST', playerId: 'P52', teamId: 'T4' },
      { minute: 77, type: 'GOAL', playerId: 'P52', teamId: 'T4' },
      { minute: 77, type: 'ASSIST', playerId: 'P48', teamId: 'T4' },
      {
        minute: 64,
        type: 'CARD',
        playerId: 'P2',
        teamId: 'T1',
        card: 'YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P1'],
      awayGKIds: ['P46'],
    },
  },
  {
    id: 'M18',
    stageId: 'STAGE-GRP-1',
    groupId: 'A',
    round: 3,
    date: '2025-08-29T13:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T2',
    awayTeamId: 'T3',
    score: { home: 0, away: 0 },
    events: [
      {
        minute: 36,
        type: 'CARD',
        playerId: 'P18',
        teamId: 'T2',
        card: 'YELLOW',
      },
      {
        minute: 74,
        type: 'CARD',
        playerId: 'P32',
        teamId: 'T3',
        card: 'YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P16'],
      awayGKIds: ['P31'],
    },
  },
  {
    id: 'M19',
    stageId: 'STAGE-GRP-1',
    groupId: 'B',
    round: 3,
    date: '2025-08-29T14:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T5',
    awayTeamId: 'T8',
    score: { home: 3, away: 1 },
    events: [
      { minute: 12, type: 'GOAL', playerId: 'P33', teamId: 'T5' },
      { minute: 12, type: 'ASSIST', playerId: 'P34', teamId: 'T5' },
      { minute: 44, type: 'GOAL', playerId: 'P37', teamId: 'T5' },
      { minute: 44, type: 'ASSIST', playerId: 'P31', teamId: 'T5' },
      { minute: 55, type: 'GOAL', playerId: 'P112', teamId: 'T8' },
      { minute: 55, type: 'ASSIST', playerId: 'P109', teamId: 'T8' },
      { minute: 81, type: 'GOAL', playerId: 'P36', teamId: 'T5' },
      { minute: 81, type: 'ASSIST', playerId: 'P38', teamId: 'T5' },
      {
        minute: 72,
        type: 'CARD',
        playerId: 'P108',
        teamId: 'T8',
        card: 'YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P61'],
      awayGKIds: ['P106'],
    },
  },
  {
    id: 'M20',
    stageId: 'STAGE-GRP-1',
    groupId: 'B',
    round: 3,
    date: '2025-08-29T15:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T6',
    awayTeamId: 'T7',
    score: { home: 2, away: 2 },
    events: [
      { minute: 21, type: 'GOAL', playerId: 'P79', teamId: 'T6' },
      { minute: 21, type: 'ASSIST', playerId: 'P83', teamId: 'T6' },
      { minute: 39, type: 'GOAL', playerId: 'P93', teamId: 'T7' },
      { minute: 39, type: 'ASSIST', playerId: 'P95', teamId: 'T7' },
      { minute: 61, type: 'GOAL', playerId: 'P82', teamId: 'T6' },
      { minute: 61, type: 'ASSIST', playerId: 'P81', teamId: 'T6' },
      { minute: 73, type: 'GOAL', playerId: 'P97', teamId: 'T7' },
      { minute: 73, type: 'ASSIST', playerId: 'P91', teamId: 'T7' },
      {
        minute: 64,
        type: 'CARD',
        playerId: 'P76',
        teamId: 'T6',
        card: 'YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P76'],
      awayGKIds: ['P91'],
    },
  },
  {
    id: 'M21',
    stageId: 'STAGE-GRP-1',
    groupId: 'C',
    round: 3,
    date: '2025-08-29T16:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T9',
    awayTeamId: 'T12',
    score: { home: 1, away: 2 },
    events: [
      { minute: 18, type: 'GOAL', playerId: 'P124', teamId: 'T9' },
      { minute: 18, type: 'ASSIST', playerId: 'P122', teamId: 'T9' },
      { minute: 37, type: 'GOAL', playerId: 'P171', teamId: 'T12' },
      { minute: 37, type: 'ASSIST', playerId: 'P169', teamId: 'T12' },
      { minute: 75, type: 'GOAL', playerId: 'P174', teamId: 'T12' },
      { minute: 75, type: 'ASSIST', playerId: 'P176', teamId: 'T12' },
      {
        minute: 82,
        type: 'CARD',
        playerId: 'P125',
        teamId: 'T9',
        card: 'YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P121'],
      awayGKIds: ['P166'],
    },
  },
  {
    id: 'M22',
    stageId: 'STAGE-GRP-1',
    groupId: 'C',
    round: 3,
    date: '2025-08-29T17:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T10',
    awayTeamId: 'T11',
    score: { home: 2, away: 2 },
    events: [
      { minute: 14, type: 'GOAL', playerId: 'P138', teamId: 'T10' },
      { minute: 14, type: 'ASSIST', playerId: 'P137', teamId: 'T10' },
      { minute: 31, type: 'GOAL', playerId: 'P152', teamId: 'T11' },
      { minute: 31, type: 'ASSIST', playerId: 'P153', teamId: 'T11' },
      { minute: 59, type: 'GOAL', playerId: 'P140', teamId: 'T10' },
      { minute: 59, type: 'ASSIST', playerId: 'P142', teamId: 'T10' },
      { minute: 78, type: 'GOAL', playerId: 'P156', teamId: 'T11' },
      { minute: 78, type: 'ASSIST', playerId: 'P158', teamId: 'T11' },
      {
        minute: 66,
        type: 'CARD',
        playerId: 'P147',
        teamId: 'T10',
        card: 'YELLOW',
      },
    ],
    lineups: {
      homeGKIds: ['P136'],
      awayGKIds: ['P151'],
    },
  },
  {
    id: 'M23',
    stageId: 'STAGE-GRP-1',
    groupId: 'D',
    round: 3,
    date: '2025-08-29T18:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T13',
    awayTeamId: 'T16',
    score: { home: 2, away: 0 },
    events: [
      { minute: 11, type: 'GOAL', playerId: 'P183', teamId: 'T13' },
      { minute: 11, type: 'ASSIST', playerId: 'P185', teamId: 'T13' },
      { minute: 47, type: 'GOAL', playerId: 'P189', teamId: 'T13' },
      { minute: 47, type: 'ASSIST', playerId: 'P193', teamId: 'T13' },
      {
        minute: 74,
        type: 'CARD',
        playerId: 'P229',
        teamId: 'T16',
        card: 'RED',
      },
    ],
    lineups: {
      homeGKIds: ['P181'],
      awayGKIds: ['P226'],
    },
  },
  {
    id: 'M24',
    stageId: 'STAGE-GRP-1',
    groupId: 'D',
    round: 3,
    date: '2025-08-29T19:00:00Z',
    status: 'FINISHED',
    homeTeamId: 'T14',
    awayTeamId: 'T15',
    score: { home: 2, away: 2 },
    events: [
      { minute: 14, type: 'GOAL', playerId: 'P198', teamId: 'T14' },
      { minute: 14, type: 'ASSIST', playerId: 'P207', teamId: 'T14' },
      {
        minute: 33,
        type: 'CARD',
        playerId: 'P219',
        teamId: 'T15',
        card: 'YELLOW',
      },
      { minute: 52, type: 'GOAL', playerId: 'P213', teamId: 'T15' },
      { minute: 52, type: 'ASSIST', playerId: 'P214', teamId: 'T15' },
      { minute: 67, type: 'OWN_GOAL', playerId: 'P203', teamId: 'T14' },
      {
        minute: 74,
        type: 'CARD',
        playerId: 'P219',
        teamId: 'T15',
        card: 'SECOND_YELLOW',
      },
      { minute: 81, type: 'GOAL', playerId: 'P200', teamId: 'T14' },
      { minute: 81, type: 'ASSIST', playerId: 'P206', teamId: 'T14' },
    ],
    lineups: {
      homeGKIds: ['P196'],
      awayGKIds: ['P211'],
    },
  },
];

function upsertOneMatch(tx: PrismaClient, m: SeedMatch) {
  return tx.match.upsert({
    where: { id: m.id },
    update: {
      stageId: m.stageId,
      groupId: m.groupId ?? null,
      round: m.round ?? null,
      date: new Date(m.date),
      status: m.status,
      homeTeamId: m.homeTeamId,
      awayTeamId: m.awayTeamId,
      homeScore: m.score?.home ?? null,
      awayScore: m.score?.away ?? null,
      homeGKIds: m.lineups?.homeGKIds ?? [],
      awayGKIds: m.lineups?.awayGKIds ?? [],
      // wyczyść stare eventy i wgraj aktualne
      events: m.events?.length
        ? {
            deleteMany: {}, // usuń wszystkie powiązane eventy
            create: m.events.map((e) => ({
              minute: e.minute,
              type: e.type,
              playerId: e.playerId,
              teamId: e.teamId,
              card: e.card ?? null,
            })),
          }
        : { deleteMany: {} },
    },
    create: {
      id: m.id,
      stageId: m.stageId,
      groupId: m.groupId ?? null,
      round: m.round ?? null,
      date: new Date(m.date),
      status: m.status,
      homeTeamId: m.homeTeamId,
      awayTeamId: m.awayTeamId,
      homeScore: m.score?.home ?? null,
      awayScore: m.score?.away ?? null,
      homeGKIds: m.lineups?.homeGKIds ?? [],
      awayGKIds: m.lineups?.awayGKIds ?? [],
      events:
        m.events && m.events.length
          ? {
              create: m.events.map((e) => ({
                minute: e.minute,
                type: e.type,
                playerId: e.playerId,
                teamId: e.teamId,
                card: e.card ?? null,
              })),
            }
          : undefined,
    },
  });
}

async function main() {
  console.log(`\nSeeding tournament "${TOURNAMENT_ID}" (mode=${MODE})...\n`);

  if (MODE === 'reset') {
    await prisma.matchEvent.deleteMany({
      where: { match: { stage: { tournamentId: TOURNAMENT_ID } } },
    });
    await prisma.match.deleteMany({
      where: { stage: { tournamentId: TOURNAMENT_ID } },
    });
    await prisma.player.deleteMany({
      where: { team: { tournamentId: TOURNAMENT_ID } },
    });
    await prisma.team.deleteMany({ where: { tournamentId: TOURNAMENT_ID } });
    await prisma.group.deleteMany({ where: { tournamentId: TOURNAMENT_ID } });
    await prisma.stage.deleteMany({ where: { tournamentId: TOURNAMENT_ID } });
    await prisma.tournament.deleteMany({ where: { id: TOURNAMENT_ID } });
  }

  await prisma.tournament.upsert({
    where: { id: TOURNAMENT_ID },
    update: {
      name: 'Trawiasta Liga Piłki Nożnej Warszawa 2026',
      mode: 'LEAGUE_PLAYOFFS',
      description:
        'Trawiasta Liga Piłki Nożnej Warszawa to coroczne wydarzenie sportowe, które gromadzi drużyny z całego regionu. Edycja 2026 zapowiada się wyjątkowo emocjonująco – ponad 20 zespołów, setki kibiców i pasja, która napędza każdą akcję na boisku.',
      additionalInfo:
        'Wyniki, strzelcy bramek oraz szczegóły meczów będą uzupełniane na bieżąco po zakończeniu każdego meczu. Do zobaczenia na stadionie!',
      season: 'Edycja 2026',
      startDate: new Date('2026-01-17T12:00:00Z'),
      endDate: new Date('2026-01-31T20:30:00Z'),
      timezone: 'Europe/Warsaw',
      venue: 'PGE Narodowy',
      venueAddress: 'al. Księcia Józefa Poniatowskiego 1, 03-901 Warszawa',
      venueImageUrl: 'assets/MIEJSCA/PGE-NARODOWY-WARSZAWA.png',
    },
    create: {
      id: TOURNAMENT_ID,
      name: 'Trawiasta Liga Piłki Nożnej Warszawa 2026',
      mode: 'LEAGUE_PLAYOFFS',
      description:
        'Trawiasta Liga Piłki Nożnej Warszawa to coroczne wydarzenie sportowe, które gromadzi drużyny z całego regionu. Edycja 2026 zapowiada się wyjątkowo emocjonująco – ponad 20 zespołów, setki kibiców i pasja, która napędza każdą akcję na boisku.',
      additionalInfo:
        'Wyniki, strzelcy bramek oraz szczegóły meczów będą uzupełniane na bieżąco po zakończeniu każdego meczu. Do zobaczenia na stadionie!',
      season: 'Edycja 2026',
      startDate: new Date('2026-01-17T12:00:00Z'),
      endDate: new Date('2026-01-31T20:30:00Z'),
      timezone: 'Europe/Warsaw',
      venue: 'PGE Narodowy',
      venueAddress: 'al. Księcia Józefa Poniatowskiego 1, 03-901 Warszawa',
      venueImageUrl: 'assets/MIEJSCA/PGE-NARODOWY-WARSZAWA.png',
    },
  });

  for (const g of groups) {
    await prisma.group.upsert({
      where: { id: g.id },
      update: { name: g.name, tournamentId: TOURNAMENT_ID },
      create: {
        id: g.id,
        name: g.name,
        tournamentId: TOURNAMENT_ID,
      },
    });
  }

  for (const s of stages) {
    await prisma.stage.upsert({
      where: { id: s.id },
      update: {
        name: s.name,
        kind: s.kind,
        order: s.order,
        tournamentId: TOURNAMENT_ID,
      },
      create: {
        id: s.id,
        name: s.name,
        kind: s.kind,
        order: s.order,
        tournamentId: TOURNAMENT_ID,
      },
    });
  }

  for (const t of teams) {
    await prisma.team.upsert({
      where: { id: t.id },
      update: {
        name: t.name,
        logo: t.logo ?? null,
        tournamentId: TOURNAMENT_ID,
        groupId: t.groupId,
      },
      create: {
        id: t.id,
        name: t.name,
        logo: t.logo ?? null,
        tournamentId: TOURNAMENT_ID,
        groupId: t.groupId,
      },
    });
  }

  for (const p of players) {
    await prisma.player.upsert({
      where: { id: p.id },
      update: {
        teamId: p.teamId,
        name: p.name,
        position: p.position,
        shirtNumber: p.shirtNumber ?? null,
        healthStatus: p.healthStatus,
      },
      create: {
        id: p.id,
        teamId: p.teamId,
        name: p.name,
        position: p.position,
        shirtNumber: p.shirtNumber ?? null,
        healthStatus: p.healthStatus,
      },
    });
  }

  for (const m of matches) {
    await upsertOneMatch(prisma, m);
  }

  console.log('✅ Seed finished.');
}

main()
  .catch((e) => {
    console.error('❌ Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
